events {
worker_connections  1024;
}

http {
    server {
      listen              443 ssl;
      ssl_certificate     /certs/cert.pem;
      ssl_certificate_key /certs/key.pem;
      location / {
            return 200;
      }
    }
}