events { }

http {
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /data/data/com.termux/files/home/library/certs/cert.pem;
        ssl_certificate_key /data/data/com.termux/files/home/library/certs/key.pem;

        location / {
            return 200;
        }
    }
}
